### PR TITLE
mehrad

### PR DESCRIPTION
**Pull request by xehrad**
hi guys, its my fuck name, brainFuck name 0.o

### CODE REVIEW

**Comment by ahangarha** [comment]
Please provide description on what your pull request is going to add.

Also I think it is better to keep branch and pull request, very much issue centric and not include different and irrelevant changes in one pull request

**Comment by ahangarha** [comment]
The BF code works well. well done

**Review by mostafa-pr — COMMENTED** [review]
hi

**Review by gitygity — COMMENTED** [review]
hi

**Comment by ahangarha** [comment]
"hi" is not considered as review. Please review.

**Review by gitygity — APPROVED** [review]

**Comment by xehrad** [comment]
hi guys, its my fuck name, brainFuck name 0.o

**Review by ahangarha — APPROVED** [review]

**Review by masihtehrani — APPROVED** [review]

**Pull request merged**
