### PR TITLE
Creating BF script for ahangarha

### PR DESCRIPTION
**Pull request by ahangarha**
I have made my BF file.

I have checked it on https://tio.run/#brainfuck and it seems it is working well.

Though it a be written in lesser lines but I though it is better to keep the code more clear, so it will remain clear for maintaining and debuging ;)

### CODE REVIEW

**Review by masihtehrani — CHANGES_REQUESTED** [review]
nfinite loop!

**Comment by ahangarha** [comment]
@masihtehrani How? The loop starts from 11 and each time, it gets reduced by one. at the end, it becomes zero and we go to the section for printing the output.

I have tested the code, it works as expected.

May you explain more why it is infinite loop?

**Review by masihtehrani — APPROVED** [review]
Brave and true

**Comment by gitygity** [comment]
should we speak english language here? 
anyway i cant upload my project . plz explain the steps of forking and reviewe

**Comment by ahangarha** [comment]
@gitygity Go to the main repo, find Fork button on top right side of the page and click on it. It will make a copy (fork) of the project on your profile. on your repo, make a new branch, name it as something meaningful. Then make a new file, name it as you are asked.

Then edit the file and add your code into it. save it.

You should see an option for making a pull request based on your changes. Done.

For reviewing other's pull requests, simply go to the main repo and click on Pull Request tab. There you will see all the open Pull Requests. you can submit your comment and review.

**Pull request merged**
