### PR TITLE
Enhancing content and format of README.md

### PR DESCRIPTION
**Pull request by ahangarha**
Enhancing the content as well as fixing Markdown formatting.

### CODE REVIEW

**Review by masihtehrani — CHANGES_REQUESTED** [review]
why you have two commit for one issue
please send one commit
for continuous commit for one commit use flag --amend

**Review by masihtehrani — CHANGES_REQUESTED** [review]
first dont multiple commit for one feature
second this commit exist in another pull requset

**Comment by ahangarha** [comment]
You are right. I made change in the README.md file and made a commit. after that, I noticed one more thing to change. So, I made a second edit and therefor the second commit.

I know I should make not commit before I made all my changes.

I will try to take care of this little but important thing.

Thanks

**Comment by ahangarha** [comment]
@masihtehrani 

I think what I did is more useful and comprehensive than the one suggested by the ther friend.

I have improved the content and the format.

**Review by masihtehrani — APPROVED** [review]

**Comment by masihtehrani** [comment]
Please resolve your conflict

**Pull request closed without merging**
